<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
class Product extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [  
                'id'=>  'ff20220118pr1',            
                'name' => 'Dâu tằm',
                'price' =>  30000,
                'stock' => 20,
                'type' => 'Trái cây',
                'unit' => 'Kg',
                 'description' => 'Quả dâu tằm có lợi trong việc cải thiện lưu lượng máu trong cơ thể, kiểm soát huyết áp và làm sạch máu. Các chất chống oxy hóa từ dâu sẽ hỗ trợ thúc đẩy chức năng của các mạch máu bằng cách giữ cho chúng dẻo dai và giãn nở.',
                 'image' => '1.png',
                'status' => 1,
            ]            ,
            [  'id'=>  'fvg20220118pr2',
                'name' => 'Rau salad',
                'price' =>  10000,
                'stock' => 10,
                'type' => 'Rau củ',
                'unit' => 'Kg',
                'description' => 'Rau xanh rất giàu canxi, vitamin K cao giúp hệ xương ổn định, phát triển khỏe mạnh. Củng cố xương, cải thiện mật độ xương, làm cho chúng dày và khỏe mạnh hơn',
                'image' => '7.png',
                'status' => 1,
            ],
            [  'id'=>  'fw20220118pr3',
                'name' => 'Nước suối',
                'price' =>  7000,
                'stock' => 20,
                'type' => 'Thức uống',
                'unit' => 'Chai',
                'description' => 'Nước còn mang lại rất nhiều lợi ích cho cơ thể khi được cung cấp đầy đủ chẳng hạn như: Giúp các khớp hoạt động tốt hơn, hoặc làm cho tim khỏe mạnh hơn',
                'image' => '8.png',
                'status' => 1,
            ],
            [ 'id'=> 'ff20220118pr4',
                'name' => 'Kiwi',
                'price' =>  50000,
                'stock' => 15,
                'type' => 'Trái cây',
                'unit' => 'Kg',
                'description' => 'Kiwi vào chế độ ăn uống của mình để đạt được những lợi ích chúng mang lại, có thể dễ dàng kết hợp nó vào một số công thức nấu ăn. Rất tuyệt để thêm kiwi vào bữa sáng. ',
                'image' => '3.png',
                'status' => 1,
            ],
            [ 'id'=> 'ff20220118pr5',
                'name' => 'Cam mỹ',
                'price' =>  20000,
                'stock' => 20,
                'type' => 'Trái cây',
                'unit' => 'Kg',
                'description' => 'Quả cam rất giàu vitamin C, một dưỡng chất giúp hấp thụ sắt, làm tăng số lượng huyết sắc tố và ngăn ngừa các triệu chứng thiếu máu như mệt mỏi và chóng mặt',
                'image' => '4.png',
                'status' => 1,
            ],          
            [ 'id'=> 'fm20220118pr6',
                'name' => 'Thịt bò',
                'price' =>  62000,
                'stock' => 40,
                'type' => 'Thịt',
                'unit' => 'Gram',
                'description' => 'Thịt là nguồn cung cấp protein có vai trò chính trong xây dựng cơ bắp vì lý do đó, thịt là nguồn protein dồi dào có thể có lợi ích đặc biệt sau phẫu thuật hoặc cho các vận động viên phục hồi. ',
                'image' => '9.png',
                'status' => 1,
        ],
            [ 'id'=>  'ff23112001pr7',
                'name' => 'Nho nhật',
                'price' =>  34000,
                'stock' => 10,
                'type' => 'Trái cây',
                'unit' => 'Kg',
                'description' => 'Nho là loại quả chứa nhiều chất dinh dưỡng, chất xơ, kali... Nho cung cấp rất nhiều lợi ích sức khỏe do hàm lượng chất dinh dưỡng và chất chống oxy hóa cao. Dưới đây là 12 lợi ích sức khỏe hàng đầu của nho.',
                'image' => '5.png',
                'status' => 1,
            ],
            [ 'id'=>  'ff20220118pr8',
                'name' => 'Dâu tây',
                'price' =>  21000,
                'stock' => 50,
                'type' => 'Trái cây',
                'unit' => 'Kg',
                'description' => 'Dâu tây sẽ rất có ích bởi chúng có khả năng chống viêm và làm sáng da. Thêm vào đó, vitamin C trong dâu tây hạn chế các bệnh về mắt như đục thủy tinh thể.',
                'image' => '6.png',
                'status' => 1,
            ],
            [ 'id'=> 'ff20220118pr9',
            'name' => 'Táo mỹ',
            'price' =>  19000,
            'stock' => 30,
            'type' => 'Trái cây',
            'unit' => 'Kg',
            'description' => 'Táo giúp hỗ trợ giảm cân do hàm lượng chất xơ trong táo thúc đẩy cảm giác no, giảm lượng calo và tăng giảm cân. - Ăn nhiều táo giúp tăng mật độ khoáng xương, giảm nguy cơ loãng xương;',
            'image' => '2.png',
            'status' => 1,
        ],
    ]);

    }}
